### ISSUE TITLE
Persistent menu with nesting

### ISSUE THREAD

**Issue by progapandist** [hyperoslo/facebook-messenger#134]
Hello! 

Facebook has recently updated their Messenger Platform with the support for nesting in the persistent menu. However, it doesn't seem that this feature is supported in the gem. When I tried to add a nested `call_to_actions` array to the hash under `Facebook::Messenger::Thread.set`, I've got this error: 

`Facebook::Messenger::Thread::Error: (#100) Invalid keys "call_to_actions" were found in param "call_to_actions[0]".`

Do you plan on updating your gem's API in order to set nested menus? I also tried to set my menu to the new format manually, by sending a POST request directly to Graph as described [here](https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu) without using `Thread.set` at all, and I get a success response from Graph, but every time facebook-messengers starts, these changes seem to be overridden and the update to Persistent Menu doesn't show. I'm pretty sure it's not a cashing issue.   

Please, correct me if I'm getting it wrong, and thank you in advance!

**Comment by fcatuhe** [comment]
Hello @progapandist, it seems thread_settings is deprecated now, the new way to do since Send API 1.4 is to use messenger_profile.

I'm updating my bot menus 'by hand' at the moment, but will try to make a pull request on that topic.

Regarding the sort of caching in Messenger, I always have to delete the conversation with my bot to force the update of the persistent menu. From experience with users, after some time the menu updates itself, but too long time for testing purposes.

See you fellow Wagon buddy ;-)

**Comment by progapandist** [comment]
Hello @fcatuhe, nice to see a fellow Wagoner indeed! Thanks for sharing, I was thinking a menu should update at some point after a "manual" POST request to the new Facebook's endpoint, but deleting/reinitiating chats did nothing in testing. I see now that there is an open PR from a month ago that tries to address this issue, and a discussion about that. I guess we have to wait )

**Comment by fcatuhe** [comment]
OK it seems I figured how to implement this in my last pull request #135

**Comment by progapandist** [comment]
Great! Hope it gets merged soon

**Comment by jgorset** [comment]
Thanks for the great pull request, @fcatuhe! I'll close this, then.
