### ISSUE TITLE
How to use Thread?

### ISSUE THREAD

**Issue by FlintOFF** [hyperoslo/facebook-messenger#57]
Hi.
I can't understand how to use 'Thread'.
I'm tried add greeting message to 'Bot.on :optin',  but when I interacts to chat (after delete chat on my phone) I don't see greeting message.
Please explain, how to use thread.

**Comment by dmitryshagin** [comment]
It looks like Facebook bug, I have it ~70% times when I delete chat. It usually worjs on m.me, usually fails on iPhone, abd worjs time-to time in Android. Try to clear all caches and restart messenger app after you remove your chat. It worked for me. As for the code - I'd successfully used samples from readme, thet seems to be fine.

**Comment by FlintOFF** [comment]
Thanks. 
Button 'Get started' already present.
But 'greeting message' still lost.

**Comment by dmitryshagin** [comment]
Hmmm. It seems to be also a FB bug. I tried to reproduce it, and it seems to be platform-dependent and account status-dependent. Sometimes I and see greeting, and sometimes I dont. Without changing the code. And I'm also monitoring incoming traffic - there are no bad requests from Facebook. Please try again with clean account on different devices - because this greeting meage also disappears with plenty of bots, including CNN.

**Comment by enderahmetyurt** [comment]
Now I am try to show greeting message. For desktop Facebook messenger you can live the chat and delete all messages. After doing that, try to send message again you can see the message. For mobile Facebook messenger app on iOS you can kill the app process and start it again if you delete the chat like desktop. Btw you should start server where your app works on if you change the greeting message. 

In here my problem is that greeting button "Get started" cannot be displayed. Anyone solved it?
