### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by kurko** [hyperoslo/facebook-messenger#64]
Things that need improvement:
- [ ] threadsafe configuration
- [ ] threadsafe delivery of messages

Without these improvements only really simple apps can be implemented with this gem.
---

**Configuration:** because the configuration is managed globally (e.g `Facebook::Messenger.config.access_token=`), instead of per instance, it's not possible to use this gem in the scenario where the application might connect at the same time to multiple pages. For instance, think about using something like Sidekiq.

Ideally, the subscription code should be something like

``` ruby
subscription = Facebook::Messenger::Subscriptions.new(
  access_token: '...',
  app_secret: '...',
  verify_token: '...'
)
subscription.create
```

**Message delivery:** again, because we can't guarantee one access token in a particular delivery, the global access token could leak into a delivery for another page. We should be able to explicitly pass `access_token` in the `deliver` method.

Is it something the admins are in accordance?

<sub>I'm not sure I'll have the time myself to open a PR soon, but I'll leave this issue registered here and try to get to it.</sub>

**Comment by jgorset** [comment]
Thanks @kurko! We've only needed simple bots so far, but this would be a great improvement. We could probably even keep the existing API for simple use cases by just building it on top of a subscription model like that. We'd be very happy for pull requests (from you or anyone else or even ourselves when we need it)! :cake: will be had!

**Comment by sorich87** [comment]
Just learned about thread safety in Ruby. I was doing `Facebook::Messenger.config.access_token = XXX` before every call to the API. Please don't laugh. 😂 

I added it to my tasks list. I'll do it if no one does before I get to it.

**Comment by jgorset** [comment]
Cool @sorich87!

**Comment by kurko** [comment]
👍

@sorich87 be careful with that. If you're using Sidekiq (which I believe is the best approach) or something that multi-threaded, you'll send messages to the wrong users randomly 😁

**Comment by sorich87** [comment]
@kurko yes, I'm using Sidekiq. For now, there's a very very small chance that different messages are queued simultaneously. But fixing it is high on my tasks list. Thanks 😄

**Comment by sorich87** [comment]
@kurko @jgorset what about using Thread.current like I18n does? https://github.com/svenfuchs/i18n/blob/aee7b3f6072fba3f54798a280bd6007536b039cd/lib/i18n.rb#L17. It looks like it won't require much changes. Any drawback?

**Comment by jgorset** [comment]
Maybe! What would it be like to use the library with that change, @sorich87?

I like @kurko's idea of initializing something with an access token, but it can't be `Subscription`; that's something you do only once to hook the page up to your Facebook application (and it's even possible to do that by clicking a button in the application settings on developers.facebook.com now).

What about `Bot`, though? It's a module now, but if we make it a class we can instantiate it with the necessary configuration:

```ruby
# Old
Facebook::Messenger.configure do |config|
  config.access_token = ENV['ACCESS_TOKEN']
  config.verify_token = ENV['VERIFY_TOKEN']
end

Bot.on :message do |message|
  Bot.deliver recipient: message.sender,
    message: {
      text: 'Hello, human!'
    }
end

# New?
bot = Bot.new(access_token, verify_token)
bot.on :message do |message|
  Bot.deliver recipient: message.sender,
    message: {
      text: 'Hello, human!'
    }
end
```

What do you think?

**Comment by frodsan** [comment]
I think `New?` is good and it can be backwards-compatible.

**Comment by jgorset** [comment]
On second thought, that interface doesn't really solve the use case of using the same bot across multiple pages very well. You'd have to initialize a bunch of bots and register the same methods on each of them, which seems a weird thing to do:

```ruby
pages.each do |access_token, verify_token, app_secret|
  bot = Bot.new [...]
  
  bot.on [...]
end
```

You'd be able to make your bot behave differently for each page with this approach, but that's probably not a good idea anyway (and if one absolutely must it's still possible to do by checking `Incoming::Message.recipient`).

It would also be tricky to get `Facebook::Messenger::Server` to play nice with this approach because it needs `verify_token` and `app_secret` to handle incoming messages.

We might instead consider to allow the configuration of multiple pages:

```ruby
Facebook::Messenger.configure do |config|
  pages.each do |access_token, verify_token, app_secret|
    config.pages.add access_token: access_token, verify_token: verify_token, app_secret: app_secret
  end
end

Bot.on :message do |message|
  Bot.deliver recipient: message.sender,
    message: {
      text: 'Hello, human!'
    }
end
```

**Comment by jgorset** [comment]
I'd be interested to hear whether the above would solve your use case, @kurko.

**Comment by sorich87** [comment]
> Maybe! What would it be like to use the library with that change, @sorich87?

@jgorset the change would be this https://github.com/botamp/facebook-messenger/commit/e70210b44a533ae8c100ad2f1a4dbd446bd24527. And you would use it like:

```
Facebook::Messenger.configure do |config|
  config.verify_token = ENV['VERIFY_TOKEN']
  config.app_secret = ENV['APP_SECRET']
end

Bot.on :message do |message|
  page = Page.find_by(facebook_id: message.recipient.id)
  Facebook::Messenger.config.access_token = page.access_token
  Bot.deliver recipient: message.sender,
    message: {
      text: 'Hello, human!'
    }
end
```

So it doesn't change the existing API.

It seems like your last example of configuration per page may work well too. How would the bot know which page config to use when delivering a message? Where would that be setup? By passing the page ID to `Bot.deliver`?

**Comment by echan00** [comment]
It would be great to see this feature.

I don't know if I'm technical enough to do it myself, but if one of you send me pointers I'd be happy to try.

**Comment by jgorset** [comment]
I'm not sure that'll work, @sorich87, because `Facebook::Messenger::Server` (the layer that ends up calling the code you registered with `Bot.on`) needs the verify token to accept subscriptions and the app secret to verify the integrity of incoming messages. It'll have to be configured earlier, then, like in [my example](https://github.com/hyperoslo/facebook-messenger/issues/64#issuecomment-247686875).

> How would the bot know which page config to use when delivering a message? Where would that be setup? By passing the page ID to Bot.deliver?

Yeah. We could pass the Facebook Page ID to `Incoming::Message`, `Incoming::Postback` etc., but with the current interface we can't really get around having the developer pass it to `Bot.deliver` themselves:

```ruby
Bot.on :message do |message|
  Bot.deliver {
    page: message.page,
    recipient: message.sender,
    message: {
      text: 'Hello, human!'
    }
  }
end
```

I can't think of a lot of use cases for responding to a different user on a different page, though, so that's getting pretty verbose. Maybe we could introduce a convenience method on `Incoming::Message`, `Incoming::Postback` etc. called `reply` that would just take care of that for you?

```ruby
Bot.on :message do |message|
  message.reply message: 'Hello, human'
end
```

What do you think, guys?

**Comment by jgorset** [comment]
Feel free to have a go at it, @echan00!

**Comment by sorich87** [comment]
> needs the verify token to accept subscriptions and the app secret to verify the integrity of incoming messages

yes, you're right. In my use case, it's just one app for multiple page so I was overlooking the fact it could be multiple apps.

> I think I like it. What do you think?

That would be great! You can't send to another user on a different page anyway since the recipient ID is page-scoped (unless I don't understand how PSID work).

**Comment by jgorset** [comment]
> That would be great! You can't send to another user on a different page anyway since the recipient ID is page-scoped (unless I don't understand how PSID work).

Right, but if you're managing multiple pages you might have saved the PSID of another user to forward the message to or something. Not really a common use case, but something that you'd still be able to do with `Bot.deliver` on your own.

**Comment by pjpires** [comment]
Hi guys! First of all, thanks for the great work with the gem. 

I'm currently using it in a project where we will allow users to configure their own bot and link it to a Facebook page they manage.

I found [this older fork](https://github.com/hyperoslo/facebook-messenger/compare/master...perrypelletier:multi-app) and I thought it was a clean approach.

So the changes I came up with to make it work with multiple bots are here: [https://github.com/hyperoslo/facebook-messenger/compare/master...pjpires:master](https://github.com/hyperoslo/facebook-messenger/compare/master...pjpires:master)
and one would integrate it in a project like this: [https://gist.github.com/pjpires/cae50d83bdb4bac0425c608ca2673384](https://gist.github.com/pjpires/cae50d83bdb4bac0425c608ca2673384)

With this, users could leverage the `config_provider_class` to implement their one mechanisms to save tokens for each bot (in my case, I'm storing them in a bots table in the DB. Also, keep in mind that in my implementation it requires each Facebook page to subscribe a single bot in the app, as I store the `page_id` in the bot model.

I would like to ask your thoughts on it, because doing it this way it would be retro-compatible with single bot implementations. And as we're picking tokens on every request/response, I think we would avoid thread safety.

**Comment by jgorset** [comment]
That's neat, @pjpires! I think that is exactly the approach we should take to enable bots to be used across several pages. If anyone's willing to make a pull request from that implementation I'd be happy to accept it.

**Comment by jgorset** [comment]
This is #84!
