### ISSUE TITLE
Mounting multiple bots in routes.rb

### ISSUE THREAD

**Issue by echan00** [hyperoslo/facebook-messenger#75]
Sorry. This is probably more of a rails question than one for this repository, but I'm not sure where to go about finding an answer.

I'm able to follow the installation guide and mount the Facebook Messenger engine without any problems. What should I do instead if I want to be able to host multiple instances of the same bot?  This will be separate bots (using the same code) but with different access tokens, app secret, etc.. 

The only way that makes sense to me is to mount separate bots doing something like this..

`mount Facebook::Messenger::Server, at: 'bot/:unique_id'`

Is this the way to do it?  Basically having a separate webhook per bot as a way to identify each bot?

**Comment by jgorset** [comment]
No worries @echan00, I think that sounds like a valid use case. That might just work, but it could prove difficult to configure the bot correctly because [we don't really support multiple bots on the same code base yet](https://github.com/hyperoslo/facebook-messenger/issues/64). I'd be very happy to accept a pull request if you need it, though!
