### ISSUE TITLE
Manually define FB variables

### ISSUE THREAD

**Issue by rkrayovskyy** [hyperoslo/facebook-messenger#94]
Hi,

since v. 0.11.0 Facebook variables are defined in global variables with predefined names, as explained in documentation:

> export ACCESS_TOKEN=EAAAG6WgW...
> export APP_SECRET=a885a...
> export VERIFY_TOKEN=95vr15g...

and an older way of defining them seems to be deprecated:
```
Facebook::Messenger.configure do |config|
  config.access_token = ENV["ACCESS_TOKEN"]
  config.app_secret   = ENV["APP_SECRET"]
  config.verify_token = ENV["VERIFY_TOKEN"]
end
```

However, I use another names for facebook vars - how can I still manually define them?

thanks!

UPD: with defining FB variables as expected, the following error fired up:

> /facebook-messenger-0.11.0/lib/facebook/messenger/thread.rb:17:in `set': missing keyword: access_token (ArgumentError)

(adding it here as seems to be somehow related)

**Comment by rkrayovskyy** [comment]
I figured out the second part of my question about an error:

> /facebook-messenger-0.11.0/lib/facebook/messenger/thread.rb:17:in `set': missing keyword: access_token (ArgumentError)

Need to add access_token to every Thread.set() like so:
```
Facebook::Messenger::Thread.set(
  {
  	setting_type: 'greeting',
    greeting: {
      text: 'greeting.'
    }
  },
  access_token: ENV['ACCESS_TOKEN']
)
```

Need to either document it, or (better) use global var unless other explicitly specified.

The first question about manually defining variables is still open.

thanks!

**Comment by jgorset** [comment]
Hi @rkrayovskyy! You can write your own configuration provider to use different environment variables. It won't be too different from the [default configuration provider](https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/configuration/providers/environment.rb).

**Comment by jgorset** [comment]
I documented [passing environment variables to `Thread`](https://github.com/hyperoslo/facebook-messenger/commit/11170c14cb5fb35270f5b30ae08e8af875919bf4). The reason we aren't and can't default to environment variables is that it only makes sense if you're using the default configuration provider, because that's the only thing that uses environment variables. If your bot is installed to multiple Facebook Pages or if you are using your own configuration provider to use different environment variables, it won't work.
